### PR TITLE
Animate Header CTA and fix when it shows

### LINKED ISSUE #16: Header CTA no longer showing
The Header no longer shows the 'New Chart' button on any page.

The expected functionality is to always show the button except for on the chart
builder page.

### PR DESCRIPTION
**Pull request by jaseflow**
## Description 

Header button was not showing since a change to the URLs.

This fix makes the button show on the correct pages and improves the UX by
animating the button.

- Fixes #16

### CODE REVIEW

File: src/components/Header/Header.tsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ function Header({ hidden } : HeaderProps) {
   useEffect(() => {
     if(location.pathname.includes('/create/')) {
       setCtaHidden(true)
-    } else if (!ctaHidden) {
```
Comment (simon-lang) [inline src/components/Header/Header.tsx:22]: test review comment

**Review by simon-lang — APPROVED** [review]
I approve this review
